### ISSUE TITLE
Getting a 403 during login

### ISSUE THREAD

**Issue by Chiggins** [teknogeek/Casper-API-Python#1]
So I threw this API into my fork of the https://github.com/rxw/snapy repository hoping that the code I currently have https://github.com/rxw/snapy/pull/21 would get fixed, but between the two of them I'm still getting a 403 error. I made no changes to the Casper-API-Python project besides just throwing the files all into the same directory.

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    s.login("username", "password", "test@gmail.com", "password", "key", "secret")
  File "build/bdist.linux-x86_64/egg/snapy/__init__.py", line 194, in login
  File "build/bdist.linux-x86_64/egg/snapy/__init__.py", line 96, in _request
  File "build/bdist.linux-x86_64/egg/snapy/utils.py", line 256, in request
  File "/home/chiggins/snapchat/env/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://feelinsonice-hrd.appspot.com/loq/login

And here is my code calling the CasperAPI

``` python
def login(self, username, password, gmail, gpasswd, ckey, csecret):
    """Login to Snapchat account
    Returns a dict containing user information on successful login, the
    data returned is similar to get_updates.

    :param username Snapchat username
    :param password Snapchat password
    :param gmail    Gmail address
    :param gpasswd  Gmail password
    """
    self.gmail = gmail
    self.gpasswd = gpasswd

    casper = CasperAPI(ckey, csecret)
    i = 0
    logged_in = False
    while i < 4 and logged_in == False:
        i += 1
        now = str(timestamp())
        req_token = make_request_token(STATIC_TOKEN, now)
        gauth_token = get_auth_token(gmail, gpasswd)
        self.gauth = gauth_token[0]
        self.expiry = gauth_token[1]
        string = username + "|" + password + "|" + now + "|" + req_token
        dtoken = self._get_device_token()
        self._unset_auth()
        nonce = casper.generateSnapchatNonce(username, password, now)
        attestation = casper.getSnapchatAttestation(nonce)
        r = self._request('/loq/login', {
            'username': username,
            'password': password,
            'height': 1280,
            'width': 720,
            'max_video_height': 640,
            'max_video_width': 480,
            'dsig': hmac.new(str(dtoken['dtoken1v']),string,sha256).hexdigest()[:20],
            'dtoken1i': dtoken['dtoken1i'],
            'ptoken': "ie",
            'attestation': attestation,
            'sflag': 1,
            'application_id': 'com.snapchat.android',
            'req_token': req_token
        }, {
            'now': now, 
            'gauth': self._get_gauth()
        }, None, True, 'post', {
        'X-Snapchat-Client-Auth': casper.getSnapchatClientAuth(username, password, now)
        })

        result = r.json()

        if 'updates_response' in result:
            logged_in = True
            if 'auth_token' in result['updates_response']:
                self.auth_token = result['updates_response']['auth_token']

            if 'username' in result['updates_response']:
                self.username = username

    if self.username is None and self.auth_token is None:
        raise Exception(result.get('message', 'unknown error'))

    return result
```

I've tried logging in with two different accounts but I'm still getting the same 403 error on the same URL on both of them, so I'm not exactly sure what I'm doing wrong here, if it's this CasperAPI implementation that's going a little wacky or my snapy code. Any help would be appreciated!

**Comment by Chiggins** [comment]
Am an idiot. I didn't realize that I forgot to change the User-Agent string. Changed that and everything works as it should.
